// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVFIE4Vif03m9YUfsUkIpe2P_KPbcKkm8',
    appId: '1:603215333215:web:0c415a81b4f85772d998ea',
    messagingSenderId: '603215333215',
    projectId: 'brixel-93861',
    authDomain: 'brixel-93861.firebaseapp.com',
    storageBucket: 'brixel-93861.firebasestorage.app',
    measurementId: 'G-9TX4BEZFRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvXRr0bgre9FVg_pHNpbwK7si0D1fnjWY',
    appId: '1:603215333215:android:bd53eb4aa2bd079dd998ea',
    messagingSenderId: '603215333215',
    projectId: 'brixel-93861',
    storageBucket: 'brixel-93861.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqH71mJwS0fOFyHzyPwTh_ii5ngZOtjq0',
    appId: '1:603215333215:ios:e2bfded746bc0e17d998ea',
    messagingSenderId: '603215333215',
    projectId: 'brixel-93861',
    storageBucket: 'brixel-93861.firebasestorage.app',
    iosBundleId: 'com.example.brixel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqH71mJwS0fOFyHzyPwTh_ii5ngZOtjq0',
    appId: '1:603215333215:ios:e2bfded746bc0e17d998ea',
    messagingSenderId: '603215333215',
    projectId: 'brixel-93861',
    storageBucket: 'brixel-93861.firebasestorage.app',
    iosBundleId: 'com.example.brixel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVFIE4Vif03m9YUfsUkIpe2P_KPbcKkm8',
    appId: '1:603215333215:web:9f2a2a4d642d0ae3d998ea',
    messagingSenderId: '603215333215',
    projectId: 'brixel-93861',
    authDomain: 'brixel-93861.firebaseapp.com',
    storageBucket: 'brixel-93861.firebasestorage.app',
    measurementId: 'G-QDW7GW0KLR',
  );
}
